version: "3.9"

services:
  service_a:
    build: ./service_a
    container_name: service_a
    ports:
      - "8000:8000"
      - "50051:50051"

  service_b:
    build: ./service_b
    container_name: service_b
    ports:
      - "8001:8001"
    depends_on:
      - service_a

  service_c:
    build: ./service_c
    container_name: service_c
    ports:
      - "8002:8002"
